Added time badge
AndreySBer/ForkHub pull request #55
Opened 2018-01-06 15:28 UTC by Motoaleks

2018-01-09 14:27 UTC, phansier requested changes

2018-01-09 14:27 UTC, AndreySBer commented on app/src/main/java/com/github/mobile/ui/issue/MilestoneDialogFragment.java
> +            // Due to updated milestone_item.xml this is excluded
Убери совсем

2018-01-09 14:27 UTC, AndreySBer commented on app/src/main/java/com/github/mobile/ui/milestone/MilestoneFragment.java
> + * Copyright 2017 Aleksandr Smilyanskiy
Лучше убрать
   Copyright 2017 Aleksandr Smilyanskiy

2018-01-09 14:27 UTC, AndreySBer commented on app/src/main/java/com/github/mobile/ui/milestone/MilestoneFragment.java
> +        }
Где-то тут добавить логику для закрытых майлстонов

2018-01-09 14:27 UTC, AndreySBer commented on app/src/main/res/values/strings.xml
> +    <string name="ms_time_past">past due by</string>
Добавь сразу локализацию в русский файл

2018-01-09 14:27 UTC, AndreySBer commented on app/src/main/res/values/colors.xml
> +    <color name="badge_default">#616161</color>
Поменяй на milestone_badge_…

2018-01-09 14:27 UTC, AndreySBer commented on app/src/main/res/layout/repo_milestone_item.xml
> +            android:paddingLeft="2dp"
Отступы вокруг текста увеличить немного

2018-01-16 06:36 UTC, phansier approved these changes

2018-01-16 06:40 UTC, merged